# Generated by Django 2.1.7 on 2019-05-04 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('IDBlog', models.IntegerField(primary_key=True, serialize=False)),
                ('Nazwa', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Komentarz',
            fields=[
                ('IDKomentarz', models.IntegerField(primary_key=True, serialize=False)),
                ('Data', models.DateTimeField(default=django.utils.timezone.now)),
                ('Tresc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('IDPost', models.IntegerField(primary_key=True, serialize=False)),
                ('Tytul', models.CharField(max_length=128)),
                ('Tresc', models.TextField()),
                ('Data', models.DateTimeField(default=django.utils.timezone.now)),
                ('Haslo', models.CharField(max_length=8)),
                ('Obraz', models.ImageField(upload_to='Obrazki')),
                ('IDBlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.Blog')),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Zdjecie', models.ImageField(default='domyslny_obrazek.jpg', upload_to='Obrazki')),
                ('Opis', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='komentarz',
            name='IDPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.Post'),
        ),
        migrations.AddField(
            model_name='komentarz',
            name='IDUzytkownik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='IDAutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
