# Generated by Django 2.1.7 on 2019-05-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20190504_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Haslo',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='post',
            name='Obraz',
            field=models.ImageField(blank=True, upload_to='Obrazki'),
        ),
    ]
