# Generated by Django 2.1.7 on 2019-05-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20190506_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='Opis',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
